# Generated by Django 5.1.5 on 2025-02-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_fullname_profile_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='UsernameTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
