# Generated by Django 5.1.5 on 2025-02-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_usernametime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='UsernameTime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
