# Generated by Django 5.1.5 on 2025-02-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='UsernameTime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
