# Generated by Django 5.1.5 on 2025-02-22 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_usernametime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Post'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='UsernameTime',
        ),
        migrations.AddField(
            model_name='post',
            name='Caption',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='PostedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='postmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Postimage', models.ImageField(upload_to='post')),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
            options={
                'verbose_name_plural': 'Postmedia',
            },
        ),
    ]
