# Generated by Django 5.1.5 on 2025-02-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_post_options_remove_post_usernametime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PostedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
