# Generated by Django 5.1.5 on 2025-02-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_post_posteddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='PostedTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
