# Generated by Django 5.1.5 on 2025-02-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_post_postedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='Imageorder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
