# Generated by Django 5.1.5 on 2025-03-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='CommentUser',
            new_name='Userlike',
        ),
    ]
